<?php

namespace DSL\DSLBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Diet_rulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Diet_rulesRepository extends EntityRepository
{
}
