<?php

namespace DSL\DSLBundle\Repository;

/**
 * FilePathRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilePathRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFilePathByUserIdAndDietRuleId(int $userId, int $dietRuleId) {
        return $this->findOneBy(['user' => $userId, 'dietRule' => $dietRuleId]);
    }
}

