<?php

namespace DSL\DSLBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends EntityRepository
{
}
