<?php

namespace DSL\DSLBundle\Repository;

/**
 * PeriodityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodicityRepository extends \Doctrine\ORM\EntityRepository
{
}
