hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
    
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /hwio/login
    
facebook_login:
    path: /login/check-facebook

dsl:
    resource: "@DSLBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
homepage:
    path: /home
    defaults: { _controller: DSLBundle:Default:index }
