dsl:
    resource: "@DSLBundle/Controller/"
    type:     annotation
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
homepage:
    pattern: /home
    defaults: { _controller: DSLBundle:Default:index }
