security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER,
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
#                csrf_provider: security.csrf.token_manager
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path: /start
            logout: true
            anonymous: true
            
            #HWIOAuth
            anonymous: ~
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                default_target_path: /start
                
                oauth_user_provider:
#                    service: my.oauth_aware.user_provider.service
                    service: my_user_provider
    
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/start, role: ROLE_USER }
        - {path: ^/diet_rules, role: ROLE_USER }
        - {path: ^/product, role: ROLE_USER }
        - {path: ^/meal, role: ROLE_USER }
        - {path: ^/ingredient, role: ROLE_USER }
