parameters:
#    parameter_name: value

services:
    my_user_provider:
        class: DSL\DSLBundle\Security\Core\User\FOSUBUserProvider
        arguments: ["@fos_user.user_manager",{facebook: facebook_id}]

    DSL\DSLBundle\:
        resource: '../../src/DSL/DSLBundle/*'
        exclude: '../../src/DSL/DSLBundle/{Entity,Repository,Controller}'