services:
    _defaults:
        autowire: true 
        autoconfigure: true
        public: true

    #fixturies
    meal.fixtures:
        class: DSL\DSLBundle\DataFixtures\MealFixtures

    product.fixtures:
        class: DSL\DSLBundle\DataFixtures\ProductFixtures

    user.fixtures:
        class: DSL\DSLBundle\DataFixtures\UserFixtures
        arguments:
            $adminName: %admin_name%
            $adminType: %admin_type%
            $adminRole: %admin_role%
            $adminPlainPassword: %admin_plain_password%
            $adminPopulation: %admin_population%
            $userName: %user_name%
            $userType: %user_type%
            $userRole: %user_role%
            $userPlainPassword: %user_plain_password%
            $userPopulation: %user_population%
            
    ingredient.fixtures:
        class: DSL\DSLBundle\DataFixtures\IngredientFixtures


    #repositories
    repository.meal:
        class: DSL\DSLBundle\Repository\MealRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DSL\DSLBundle\Entity\Meal
        DSL\DSLBundle\Repository\MealRepository: '@repository.meal'

    repository.created_diet:
        class: DSL\DSLBundle\Repository\CreatedDietRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DSL\DSLBundle\Entity\CreatedDiet
    DSL\DSLBundle\Repository\CreatedDietRepository: '@repository.created_diet'

    repository.product:
        class: DSL\DSLBundle\Repository\ProductsRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DSL\DSLBundle\Entity\Product
    DSL\DSLBundle\Repository\ProductsRepository: '@repository.product'

    repository.ingredient:
        class: DSL\DSLBundle\Repository\IngredientRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DSL\DSLBundle\Entity\Ingredient
        DSL\DSLBundle\Repository\IngredientRepository: '@repository.ingredient'

    repository.file_path:
        class: DSL\DSLBundle\Repository\FilePathRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DSL\DSLBundle\Entity\FilePath
        DSL\DSLBundle\Repository\FilePathRepository: '@repository.file_path'


    #calculators
    service.financial_calculator:
        class: DSL\DSLBundle\Service\Calculators\FinancialCalculator
        arguments:
            - '@repository.meal'
            - '%diet_days%'
        DSL\DSLBundle\Service\Calculators\FinancialCalculator: '@service.financial_calculator'

    service.composition_calculator:
        class: DSL\DSLBundle\Service\Calculators\CompositionCalculator
        arguments:
            - '@repository.meal'
            - '%diet_days%'
        DSL\DSLBundle\Service\Calculators\CompositionCalculator: '@service.composition_calculator'

    service.periodicity_calculator:
        class: DSL\DSLBundle\Service\Calculators\PeriodicityCalculator
        arguments:
            - '@repository.meal'
            - '%diet_days%'
        DSL\DSLBundle\Service\Calculators\PeriodicityCalculator: '@service.periodicity_calculator'


    #generators
    service.diet_generator:
        class: DSL\DSLBundle\Service\DietGenerator
        arguments:
            - '@repository.created_diet'
            - '@service.financial_calculator'
            - '@service.composition_calculator'
            - '@service.periodicity_calculator'

    service.pdf_generator:
        class: DSL\DSLBundle\Service\PdfGenerator
        arguments:
            - '@knp_snappy.pdf'
            - '%pdf_dir%'


    #other
    service.created_diet_statistics:
        class: DSL\DSLBundle\Service\CreatedDietStatistics

    service.created_diet_recipies:
        class: DSL\DSLBundle\Service\CreatedDietRecipies

    service.created_diet_helper:
        class: DSL\DSLBundle\Service\CreatedDietHelper

    service.shopping_list_helper:
        class: DSL\DSLBundle\Service\ShoppingListHelper
        arguments:
            - '@repository.created_diet'

    service.schedule:
        class: DSL\DSLBundle\Service\Schedule
        arguments:
            - '@service.pdf_generator'
            - '@service.created_diet_statistics'
            - '@service.created_diet_recipies'
            - '@twig'


    #commands
    command.dsl_pdf_remove:
        class: DSL\DSLBundle\Command\DslPdfRemoveCommand
        tags:
            name: 'console.command'
        arguments:
            - '@repository.file_path'
            - '@doctrine.orm.entity_manager'
            - '%pdf_dir%'
