services:
    _defaults:
        autowire: true 
        autoconfigure: true
        public: true

    meal.fixtures:
        class: DSL\DSLBundle\DataFixtures\MealFixtures
#        tags: ['doctrine.fixture.orm']
        
    product.fixtures:
        class: DSL\DSLBundle\DataFixtures\ProductFixtures
#        tags: ['doctrine.fixture.orm']
        
    user.fixtures:
        class: DSL\DSLBundle\DataFixtures\UserFixtures
#        tags: ['doctrine.fixture.orm']
        arguments:
            $adminName: %admin_name%
            $adminType: %admin_type%
            $adminRole: %admin_role%
            $adminPlainPassword: %admin_plain_password%
            $adminPopulation: %admin_population%
            $userName: %user_name%
            $userType: %user_type%
            $userRole: %user_role%
            $userPlainPassword: %user_plain_password%
            $userPopulation: %user_population%
            
    ingredient.fixtures:
        class: DSL\DSLBundle\DataFixtures\IngredientFixtures
    