services:
    _defaults:
        autowire: true 
        autoconfigure: true
        public: true

    meal.fixtures:
        class: DSL\DSLBundle\DataFixtures\MealFixtures

    product.fixtures:
        class: DSL\DSLBundle\DataFixtures\ProductFixtures

    user.fixtures:
        class: DSL\DSLBundle\DataFixtures\UserFixtures
        arguments:
            $adminName: %admin_name%
            $adminType: %admin_type%
            $adminRole: %admin_role%
            $adminPlainPassword: %admin_plain_password%
            $adminPopulation: %admin_population%
            $userName: %user_name%
            $userType: %user_type%
            $userRole: %user_role%
            $userPlainPassword: %user_plain_password%
            $userPopulation: %user_population%
            
    ingredient.fixtures:
        class: DSL\DSLBundle\DataFixtures\IngredientFixtures

    repository.meal:
        class: DSL\DSLBundle\Repository\MealRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DSL\DSLBundle\Entity\Meal
        DSL\DSLBundle\Repository\MealRepository: '@repository.meal'

    repository.created_diet:
        class: DSL\DSLBundle\Repository\CreatedDietRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DSL\DSLBundle\Entity\CreatedDiet
    DSL\DSLBundle\Repository\CreatedDietRepository: '@repository.created_diet'

    repository.product:
        class: DSL\DSLBundle\Repository\ProductsRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DSL\DSLBundle\Entity\Product
    DSL\DSLBundle\Repository\ProductsRepository: '@repository.product'

    repository.ingredient:
        class: DSL\DSLBundle\Repository\IngredientRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - DSL\DSLBundle\Entity\Ingredient
        DSL\DSLBundle\Repository\IngredientRepository: '@repository.ingredient'

    service.financial_calculator:
        class: DSL\DSLBundle\Service\Calculators\FinancialCalculator
        arguments:
            - '@repository.meal'
            - '%diet_days%'
        DSL\DSLBundle\Service\Calculators\FinancialCalculator: '@service.financial_calculator'

    service.composition_calculator:
        class: DSL\DSLBundle\Service\Calculators\CompositionCalculator
        arguments:
            - '@repository.meal'
            - '%diet_days%'
        DSL\DSLBundle\Service\Calculators\CompositionCalculator: '@service.composition_calculator'

    service.periodicity_calculator:
        class: DSL\DSLBundle\Service\Calculators\PeriodicityCalculator
        arguments:
            - '@repository.meal'
            - '%diet_days%'
        DSL\DSLBundle\Service\Calculators\PeriodicityCalculator: '@service.periodicity_calculator'

    service.diet_generator:
        class: DSL\DSLBundle\Service\DietGenerator
        arguments:
            - '@repository.created_diet'
            - '@service.financial_calculator'
            - '@service.composition_calculator'
            - '@service.periodicity_calculator'

    service.created_diet_statistics:
        class: DSL\DSLBundle\Service\CreatedDietStatistics

    service.created_diet_helper:
        class: DSL\DSLBundle\Service\CreatedDietHelper

    service.pdf_generator:
        class: DSL\DSLBundle\Service\PdfGenerator
        arguments:
            - '@knp_snappy.pdf'
            - '%pdf_dir%'

